name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: tests-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run ruff checks
        uses: astral-sh/ruff-action@v3
        with:
          src: "./src"

      - name: Run ruff format checks
        uses: astral-sh/ruff-action@v3
        with:
          src: "./src"
          args: "format --check --diff"

  mypy:
    name: Check mypy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run mypy checks
        run: uv run mypy --explicit-package-bases src/

      - name: Run mypy checks
        run: uv run mypy --explicit-package-bases tests/

  pyright:
    name: Check pyright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run pyright checks
        run: uv run pyright src/

  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.surrealdb-version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        surrealdb-version: ["v2.0.5", "v2.1.8", "v2.2.8", "v2.3.10", "nightly"]
    name: Core Tests - Python ${{ matrix.python-version }} - SurrealDB ${{ matrix.surrealdb-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install surrealdb
        run: |
          if [ "${{ matrix.surrealdb-version }}" = "nightly" ]; then
            curl --proto '=https' --tlsv1.2 -sSf https://install.surrealdb.com | sh -s -- --nightly
          else
            curl -sSf https://install.surrealdb.com | sh -s -- --version ${{ matrix.surrealdb-version }}
          fi

      - name: Start surrealdb
        run: surreal start --allow-all -u root -p root --log trace &

      - name: Wait for startup
        run: sleep 5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: uv sync --group dev

      - name: Build Rust extension
        run: uv run maturin develop --release

      - name: Run unit tests (HTTP)
        run: uv run pytest
        env:
          PYTHONPATH: ./src
          SURREALDB_URL: http://localhost:8000
          SURREALDB_VERSION: ${{ matrix.surrealdb-version }}
          PYTHONWARNINGS: ignore::ResourceWarning

      - name: Run unit tests (WebSocket)
        run: uv run pytest
        env:
          PYTHONPATH: ./src
          SURREALDB_URL: ws://localhost:8000
          SURREALDB_VERSION: ${{ matrix.surrealdb-version }}
          PYTHONWARNINGS: ignore::ResourceWarning

